linters:
  presets:
    - bugs
    - performance
    - unused
    - format
  disable:
    - musttag
  enable:
    - whitespace
    - misspell
    - dupl
    - gosimple

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
