name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        # criu is pre-installed in the Ubuntu 20.04 GitHub Action virtual
        # environment as a dependency for Podman
        criu_branch: ["", criu-dev]

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: build criu ${{ matrix.criu_branch }}
      if: matrix.criu_branch != ''
      run: |
        sudo apt-get install -y libprotobuf-dev libprotobuf-c-dev protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libnet-dev libcap-dev
        git clone --depth=1 --single-branch -b ${{ matrix.criu_branch }} https://github.com/checkpoint-restore/criu.git
        make -j"$(nproc)" -C criu
        sudo make -C criu install-criu PREFIX=/usr

    - name: install go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        stable: '!contains(${{ matrix.go-version }}, "beta") && !contains(${{ matrix.go-version }}, "rc")'
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: |
        # Run actual test as root as it uses CRIU.
        sudo make test
        # Test magicgen script
        make -C scripts test

    - name: Check code coverage
      if: matrix.go-version == '1.17.x' && matrix.criu_branch == 'criu-dev'
      run: |
        # Run actual test as root as it uses CRIU.
        sudo make coverage
        # Upload coverage results to codecov
        sudo -E make codecov
